// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlcodpyaclbbqveffibl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsY29kcHlhY2xiYnF2ZWZmaWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjUzNDYsImV4cCI6MjA3MzQ0MTM0Nn0.ow-q0igFWIYV8gZbXAKV1QgP5Jz03QmiHfBL6uX4D6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});